import { hashPassword } from "../../src/utils/password.js";

const baseTimestamp = "2026-04-16T00:00:00.000Z";

export function buildSeedData() {
  return {
    users: [
      {
        id: "user-admin",
        email: "admin@artisancrm.local",
        passwordHash: hashPassword("password123"),
        fullName: "Admin User",
        role: "admin",
        phone: "+233 20 000 0000",
        location: "Accra",
        specialization: null,
        bio: "Platform administrator",
        avatarUrl: null,
        isActive: true,
        createdAt: baseTimestamp,
        updatedAt: baseTimestamp,
      },
      {
        id: "user-artisan",
        email: "artisan@artisancrm.local",
        passwordHash: hashPassword("password123"),
        fullName: "Kojo Mensah",
        role: "artisan",
        phone: "+233 24 123 4567",
        location: "Kumasi",
        specialization: "Electrical",
        bio: "Residential and small business electrical repairs.",
        avatarUrl: null,
        isActive: true,
        createdAt: baseTimestamp,
        updatedAt: baseTimestamp,
      },
      {
        id: "user-customer",
        email: "customer@artisancrm.local",
        passwordHash: hashPassword("password123"),
        fullName: "Ama Owusu",
        role: "customer",
        phone: "+233 55 987 6543",
        location: "Accra",
        specialization: null,
        bio: null,
        avatarUrl: null,
        isActive: true,
        createdAt: baseTimestamp,
        updatedAt: baseTimestamp,
      },
    ],
    serviceCategories: [
      {
        id: "category-electrical",
        name: "Electrical",
        description: "Wiring, sockets and repairs",
        icon: "bolt",
        createdAt: baseTimestamp,
      },
      {
        id: "category-plumbing",
        name: "Plumbing",
        description: "Leaks, fittings and pipe work",
        icon: "droplets",
        createdAt: baseTimestamp,
      },
      {
        id: "category-carpentry",
        name: "Carpentry",
        description: "Furniture and wood repairs",
        icon: "hammer",
        createdAt: baseTimestamp,
      },
    ],
    customers: [
      {
        id: "customer-001",
        artisanId: "user-artisan",
        name: "Ama Owusu",
        email: "customer@artisancrm.local",
        phone: "+233 55 987 6543",
        address: "East Legon, Accra",
        notes: "Prefers morning visits.",
        createdAt: "2026-04-14T09:00:00.000Z",
        updatedAt: "2026-04-14T09:00:00.000Z",
      },
      {
        id: "customer-002",
        artisanId: "user-artisan",
        name: "Kwame Boateng",
        email: "kwame@example.com",
        phone: "+233 24 444 5566",
        address: "Adenta, Accra",
        notes: "Needs weekend availability.",
        createdAt: "2026-04-13T15:30:00.000Z",
        updatedAt: "2026-04-13T15:30:00.000Z",
      },
    ],
    serviceRecords: [
      {
        id: "service-001",
        artisanId: "user-artisan",
        customerId: "customer-001",
        categoryId: "category-electrical",
        description: "Ceiling fan installation",
        cost: 350,
        status: "completed",
        serviceDate: "2026-04-10",
        createdAt: "2026-04-10T13:00:00.000Z",
        updatedAt: "2026-04-10T13:00:00.000Z",
      },
      {
        id: "service-002",
        artisanId: "user-artisan",
        customerId: "customer-002",
        categoryId: "category-electrical",
        description: "Socket replacement and wiring check",
        cost: 220,
        status: "completed",
        serviceDate: "2026-04-08",
        createdAt: "2026-04-08T11:00:00.000Z",
        updatedAt: "2026-04-08T11:00:00.000Z",
      },
    ],
    appointments: [
      {
        id: "appointment-001",
        artisanId: "user-artisan",
        customerId: "customer-001",
        customerUserId: "user-customer",
        categoryId: "category-electrical",
        title: "Fix bedroom light switch",
        description: "Switch sparks occasionally.",
        scheduledDate: "2026-04-18",
        scheduledTime: "10:00:00",
        status: "confirmed",
        createdAt: "2026-04-15T10:15:00.000Z",
        updatedAt: "2026-04-15T10:15:00.000Z",
      },
      {
        id: "appointment-002",
        artisanId: "user-artisan",
        customerId: "customer-002",
        customerUserId: null,
        categoryId: "category-electrical",
        title: "Workshop power inspection",
        description: "Check frequent power cuts.",
        scheduledDate: "2026-04-19",
        scheduledTime: "14:30:00",
        status: "pending",
        createdAt: "2026-04-15T12:30:00.000Z",
        updatedAt: "2026-04-15T12:30:00.000Z",
      },
      {
        id: "appointment-003",
        artisanId: "user-artisan",
        customerId: "customer-001",
        customerUserId: "user-customer",
        categoryId: "category-electrical",
        title: "Install security light",
        description: "Completed job follow-up visit.",
        scheduledDate: "2026-04-09",
        scheduledTime: "09:00:00",
        status: "completed",
        createdAt: "2026-04-07T08:00:00.000Z",
        updatedAt: "2026-04-09T16:00:00.000Z",
      },
    ],
    feedback: [
      {
        id: "feedback-001",
        artisanId: "user-artisan",
        customerUserId: "user-customer",
        appointmentId: "appointment-003",
        rating: 5,
        comment: "Quick response and neat work.",
        createdAt: "2026-04-09T18:00:00.000Z",
      },
      {
        id: "feedback-002",
        artisanId: "user-artisan",
        customerUserId: "user-customer",
        appointmentId: "appointment-001",
        rating: 4,
        comment: "Good communication and arrived on time.",
        createdAt: "2026-04-15T19:30:00.000Z",
      },
    ],
  };
}
