ALTER TABLE users
  ADD COLUMN gender VARCHAR(30) NULL AFTER phone,
  ADD COLUMN date_of_birth DATE NULL AFTER gender,
  ADD COLUMN business_name VARCHAR(150) NULL AFTER date_of_birth,
  ADD COLUMN artisan_category VARCHAR(120) NULL AFTER business_name,
  ADD COLUMN years_experience SMALLINT UNSIGNED NULL AFTER specialization,
  ADD COLUMN address VARCHAR(255) NULL AFTER location,
  ADD COLUMN region VARCHAR(100) NULL AFTER address,
  ADD COLUMN city VARCHAR(100) NULL AFTER region,
  ADD COLUMN digital_address VARCHAR(60) NULL AFTER city,
  ADD COLUMN id_type VARCHAR(60) NULL AFTER digital_address,
  ADD COLUMN id_number VARCHAR(100) NULL AFTER id_type,
  ADD COLUMN id_card_url LONGTEXT NULL AFTER id_number,
  ADD COLUMN portfolio_urls JSON NULL AFTER id_card_url,
  ADD COLUMN price_range VARCHAR(100) NULL AFTER bio,
  ADD COLUMN availability VARCHAR(100) NULL AFTER price_range,
  ADD COLUMN working_days JSON NULL AFTER availability,
  ADD COLUMN working_hours VARCHAR(100) NULL AFTER working_days,
  ADD COLUMN whatsapp_number VARCHAR(30) NULL AFTER working_hours,
  ADD COLUMN emergency_contact_name VARCHAR(120) NULL AFTER whatsapp_number,
  ADD COLUMN emergency_contact_phone VARCHAR(30) NULL AFTER emergency_contact_name,
  ADD COLUMN payment_account_name VARCHAR(150) NULL AFTER emergency_contact_phone,
  ADD COLUMN momo_number VARCHAR(30) NULL AFTER payment_account_name,
  ADD COLUMN preferred_payment_method VARCHAR(50) NULL AFTER momo_number;
