/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerSettingsRouteImport } from './routes/customer.settings'
import { Route as CustomerRequestsRouteImport } from './routes/customer.requests'
import { Route as CustomerQuotesRouteImport } from './routes/customer.quotes'
import { Route as CustomerHistoryRouteImport } from './routes/customer.history'
import { Route as CustomerFeedbackRouteImport } from './routes/customer.feedback'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as CustomerBrowseRouteImport } from './routes/customer.browse'
import { Route as CustomerAppointmentsRouteImport } from './routes/customer.appointments'
import { Route as ArtisanSettingsRouteImport } from './routes/artisan.settings'
import { Route as ArtisanServicesRouteImport } from './routes/artisan.services'
import { Route as ArtisanRequestsRouteImport } from './routes/artisan.requests'
import { Route as ArtisanQuotesRouteImport } from './routes/artisan.quotes'
import { Route as ArtisanFeedbackRouteImport } from './routes/artisan.feedback'
import { Route as ArtisanDashboardRouteImport } from './routes/artisan.dashboard'
import { Route as ArtisanCustomersRouteImport } from './routes/artisan.customers'
import { Route as ArtisanAppointmentsRouteImport } from './routes/artisan.appointments'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSettingsRoute = CustomerSettingsRouteImport.update({
  id: '/customer/settings',
  path: '/customer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRequestsRoute = CustomerRequestsRouteImport.update({
  id: '/customer/requests',
  path: '/customer/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerQuotesRoute = CustomerQuotesRouteImport.update({
  id: '/customer/quotes',
  path: '/customer/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerHistoryRoute = CustomerHistoryRouteImport.update({
  id: '/customer/history',
  path: '/customer/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerFeedbackRoute = CustomerFeedbackRouteImport.update({
  id: '/customer/feedback',
  path: '/customer/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerBrowseRoute = CustomerBrowseRouteImport.update({
  id: '/customer/browse',
  path: '/customer/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerAppointmentsRoute = CustomerAppointmentsRouteImport.update({
  id: '/customer/appointments',
  path: '/customer/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanSettingsRoute = ArtisanSettingsRouteImport.update({
  id: '/artisan/settings',
  path: '/artisan/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanServicesRoute = ArtisanServicesRouteImport.update({
  id: '/artisan/services',
  path: '/artisan/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanRequestsRoute = ArtisanRequestsRouteImport.update({
  id: '/artisan/requests',
  path: '/artisan/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanQuotesRoute = ArtisanQuotesRouteImport.update({
  id: '/artisan/quotes',
  path: '/artisan/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanFeedbackRoute = ArtisanFeedbackRouteImport.update({
  id: '/artisan/feedback',
  path: '/artisan/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanDashboardRoute = ArtisanDashboardRouteImport.update({
  id: '/artisan/dashboard',
  path: '/artisan/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanCustomersRoute = ArtisanCustomersRouteImport.update({
  id: '/artisan/customers',
  path: '/artisan/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtisanAppointmentsRoute = ArtisanAppointmentsRouteImport.update({
  id: '/artisan/appointments',
  path: '/artisan/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin/activity',
  path: '/admin/activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/artisan/appointments': typeof ArtisanAppointmentsRoute
  '/artisan/customers': typeof ArtisanCustomersRoute
  '/artisan/dashboard': typeof ArtisanDashboardRoute
  '/artisan/feedback': typeof ArtisanFeedbackRoute
  '/artisan/quotes': typeof ArtisanQuotesRoute
  '/artisan/requests': typeof ArtisanRequestsRoute
  '/artisan/services': typeof ArtisanServicesRoute
  '/artisan/settings': typeof ArtisanSettingsRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/browse': typeof CustomerBrowseRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/feedback': typeof CustomerFeedbackRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/requests': typeof CustomerRequestsRoute
  '/customer/settings': typeof CustomerSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/artisan/appointments': typeof ArtisanAppointmentsRoute
  '/artisan/customers': typeof ArtisanCustomersRoute
  '/artisan/dashboard': typeof ArtisanDashboardRoute
  '/artisan/feedback': typeof ArtisanFeedbackRoute
  '/artisan/quotes': typeof ArtisanQuotesRoute
  '/artisan/requests': typeof ArtisanRequestsRoute
  '/artisan/services': typeof ArtisanServicesRoute
  '/artisan/settings': typeof ArtisanSettingsRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/browse': typeof CustomerBrowseRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/feedback': typeof CustomerFeedbackRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/requests': typeof CustomerRequestsRoute
  '/customer/settings': typeof CustomerSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/artisan/appointments': typeof ArtisanAppointmentsRoute
  '/artisan/customers': typeof ArtisanCustomersRoute
  '/artisan/dashboard': typeof ArtisanDashboardRoute
  '/artisan/feedback': typeof ArtisanFeedbackRoute
  '/artisan/quotes': typeof ArtisanQuotesRoute
  '/artisan/requests': typeof ArtisanRequestsRoute
  '/artisan/services': typeof ArtisanServicesRoute
  '/artisan/settings': typeof ArtisanSettingsRoute
  '/customer/appointments': typeof CustomerAppointmentsRoute
  '/customer/browse': typeof CustomerBrowseRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/customer/feedback': typeof CustomerFeedbackRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/requests': typeof CustomerRequestsRoute
  '/customer/settings': typeof CustomerSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/users'
    | '/artisan/appointments'
    | '/artisan/customers'
    | '/artisan/dashboard'
    | '/artisan/feedback'
    | '/artisan/quotes'
    | '/artisan/requests'
    | '/artisan/services'
    | '/artisan/settings'
    | '/customer/appointments'
    | '/customer/browse'
    | '/customer/dashboard'
    | '/customer/feedback'
    | '/customer/history'
    | '/customer/quotes'
    | '/customer/requests'
    | '/customer/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/users'
    | '/artisan/appointments'
    | '/artisan/customers'
    | '/artisan/dashboard'
    | '/artisan/feedback'
    | '/artisan/quotes'
    | '/artisan/requests'
    | '/artisan/services'
    | '/artisan/settings'
    | '/customer/appointments'
    | '/customer/browse'
    | '/customer/dashboard'
    | '/customer/feedback'
    | '/customer/history'
    | '/customer/quotes'
    | '/customer/requests'
    | '/customer/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/users'
    | '/artisan/appointments'
    | '/artisan/customers'
    | '/artisan/dashboard'
    | '/artisan/feedback'
    | '/artisan/quotes'
    | '/artisan/requests'
    | '/artisan/services'
    | '/artisan/settings'
    | '/customer/appointments'
    | '/customer/browse'
    | '/customer/dashboard'
    | '/customer/feedback'
    | '/customer/history'
    | '/customer/quotes'
    | '/customer/requests'
    | '/customer/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ArtisanAppointmentsRoute: typeof ArtisanAppointmentsRoute
  ArtisanCustomersRoute: typeof ArtisanCustomersRoute
  ArtisanDashboardRoute: typeof ArtisanDashboardRoute
  ArtisanFeedbackRoute: typeof ArtisanFeedbackRoute
  ArtisanQuotesRoute: typeof ArtisanQuotesRoute
  ArtisanRequestsRoute: typeof ArtisanRequestsRoute
  ArtisanServicesRoute: typeof ArtisanServicesRoute
  ArtisanSettingsRoute: typeof ArtisanSettingsRoute
  CustomerAppointmentsRoute: typeof CustomerAppointmentsRoute
  CustomerBrowseRoute: typeof CustomerBrowseRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerFeedbackRoute: typeof CustomerFeedbackRoute
  CustomerHistoryRoute: typeof CustomerHistoryRoute
  CustomerQuotesRoute: typeof CustomerQuotesRoute
  CustomerRequestsRoute: typeof CustomerRequestsRoute
  CustomerSettingsRoute: typeof CustomerSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/settings': {
      id: '/customer/settings'
      path: '/customer/settings'
      fullPath: '/customer/settings'
      preLoaderRoute: typeof CustomerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/requests': {
      id: '/customer/requests'
      path: '/customer/requests'
      fullPath: '/customer/requests'
      preLoaderRoute: typeof CustomerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/quotes': {
      id: '/customer/quotes'
      path: '/customer/quotes'
      fullPath: '/customer/quotes'
      preLoaderRoute: typeof CustomerQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/history': {
      id: '/customer/history'
      path: '/customer/history'
      fullPath: '/customer/history'
      preLoaderRoute: typeof CustomerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/feedback': {
      id: '/customer/feedback'
      path: '/customer/feedback'
      fullPath: '/customer/feedback'
      preLoaderRoute: typeof CustomerFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/browse': {
      id: '/customer/browse'
      path: '/customer/browse'
      fullPath: '/customer/browse'
      preLoaderRoute: typeof CustomerBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/appointments': {
      id: '/customer/appointments'
      path: '/customer/appointments'
      fullPath: '/customer/appointments'
      preLoaderRoute: typeof CustomerAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/settings': {
      id: '/artisan/settings'
      path: '/artisan/settings'
      fullPath: '/artisan/settings'
      preLoaderRoute: typeof ArtisanSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/services': {
      id: '/artisan/services'
      path: '/artisan/services'
      fullPath: '/artisan/services'
      preLoaderRoute: typeof ArtisanServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/requests': {
      id: '/artisan/requests'
      path: '/artisan/requests'
      fullPath: '/artisan/requests'
      preLoaderRoute: typeof ArtisanRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/quotes': {
      id: '/artisan/quotes'
      path: '/artisan/quotes'
      fullPath: '/artisan/quotes'
      preLoaderRoute: typeof ArtisanQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/feedback': {
      id: '/artisan/feedback'
      path: '/artisan/feedback'
      fullPath: '/artisan/feedback'
      preLoaderRoute: typeof ArtisanFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/dashboard': {
      id: '/artisan/dashboard'
      path: '/artisan/dashboard'
      fullPath: '/artisan/dashboard'
      preLoaderRoute: typeof ArtisanDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/customers': {
      id: '/artisan/customers'
      path: '/artisan/customers'
      fullPath: '/artisan/customers'
      preLoaderRoute: typeof ArtisanCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artisan/appointments': {
      id: '/artisan/appointments'
      path: '/artisan/appointments'
      fullPath: '/artisan/appointments'
      preLoaderRoute: typeof ArtisanAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/admin/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  ArtisanAppointmentsRoute: ArtisanAppointmentsRoute,
  ArtisanCustomersRoute: ArtisanCustomersRoute,
  ArtisanDashboardRoute: ArtisanDashboardRoute,
  ArtisanFeedbackRoute: ArtisanFeedbackRoute,
  ArtisanQuotesRoute: ArtisanQuotesRoute,
  ArtisanRequestsRoute: ArtisanRequestsRoute,
  ArtisanServicesRoute: ArtisanServicesRoute,
  ArtisanSettingsRoute: ArtisanSettingsRoute,
  CustomerAppointmentsRoute: CustomerAppointmentsRoute,
  CustomerBrowseRoute: CustomerBrowseRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerFeedbackRoute: CustomerFeedbackRoute,
  CustomerHistoryRoute: CustomerHistoryRoute,
  CustomerQuotesRoute: CustomerQuotesRoute,
  CustomerRequestsRoute: CustomerRequestsRoute,
  CustomerSettingsRoute: CustomerSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
